name: Deploy to VPS Alibaba
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PASS }}
          script: |
            cd /var/www/html/stage/music/
            git pull origin master