name: MicroSvcCICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Login to DockerHub
      uses : docker/login-action@v1
      with :
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push Client
      id : docker_build1
      uses : docker/build-push-action@v2
      with :
        push: true
        file: ./client/Dockerfile
        context: ./client
        tags: adaptivenetlab/research:clientv2

    - name: Build & Push Comments
      id : docker_build2
      uses : docker/build-push-action@v2
      with :
        push: true
        file: ./comments/Dockerfile
        context: ./comments
        tags: adaptivenetlab/research:commentsv2
        
    - name: Build & Push Posts
      id : docker_build3
      uses : docker/build-push-action@v2
      with :
        push: true
        file: ./posts/Dockerfile
        context: ./posts
        tags: adaptivenetlab/research:postsv2